services:
  - type: web
    name: md-converter
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/Magnifytools/md-converter
    branch: main
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
