services:
  - type: web
    name: file-to-md
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/Magnifytools/magnify-workspace
    rootDir: file-to-md/file-to-md-app
    branch: main
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
